### ISSUE TITLE
point à corriger ou pour y passer plus de temps

### ISSUE THREAD

**Issue by avaysse** [vguillemot/debuter#10]
Passer plus de temps:
- Les booléens
- En dire plus sur les opérations en termes généraux (sur tous les types d'objets y compris les booléens)
- Nombre de lignes et colonnes 

Corriger:
Lundi PM (objets):
- Slide 9: parenthèse fermante du bullet point 2 + "(" et ")"
- Slide 13: passr les "," de l'exemple en ";" ?
- Slides 58:61 : les formules ne passent pas sur le pdf
- ajouter dim head nrow ncol
- letters et LETTERS : on s'en est servi => soit on décrit, soit on évite
- comment ajouter une colonne

ggplot
- slide 20: summary (vitc=sum(vitamineC>10àà :  ajouter une etape et simpifier l'esxemple et l'exercice 
- 46 alpha est opacité, pas transparence
- 48 titre du graph doit correspondre au code

**Comment by vguillemot** [comment]
- Espace manquant entre "ggplot2" et "favoris" Visu slide 3
- Enlever "with" dans Visu slide 32
