### ISSUE TITLE
bilan des modifications à faire 2022

### ISSUE THREAD

**Issue by avaysse** [vguillemot/debuter#13]
Refaire les pdf: ils ne sont pas tous à jour par rapport aux html

Passer en revue les durée des quizz

dépendances debuter:
- readxl
- kableextra
- pheatmap
- pander
- png

Slides du lundi matin: slide 10 "entier de 7 à 7"

fruits du lundi est affiché comme un dataframe pour les étudiants, un tibble dans la slide

Mardi PM ggplot
slide 11: Energie1 -> Energie

déplacer l'explication de la fonction cut qui est dans ggplot vers l'exeple dplyr

slide 20 aes: double exemple avec "x=" explicite dans 1 ?
slide 21 utilisation de sum sur 1 booléen => aplique avant ? 
slide 25 mise en page

Changer les donées fruits pour avoir un ID unique (pivot_longer & pivot_wider

slide 41 La theme

color slide 4 ggplot -> ggvenn
slide 14-16: ordre des palettes (cohérence entre slides)
ajouter colour picker dans les dépendances de debuter

Ajouter l'enregistrement de fichier xlsx

**Comment by vguillemot** [comment]
Slide 9 import/export : skip = 2 et pas 3. Attention cette erreur a peut-être été commise ailleurs

**Comment by avaysse** [comment]
Faire changer l'intitulé de la formation : faire enlever le "statistiques" dans "Initiation au logiciel R & statistiques"
