### ISSUE TITLE
page d'instruction et prérequis

### ISSUE THREAD

**Issue by avaysse** [vguillemot/debuter#4]
Pour le mail de la formation interne AVANT formation

**Comment by avaysse** [comment]
Bien préciser qu'il faut avoir des data perso, et que sinon, la formation dure 1 jour de moins

**Comment by vguillemot** [comment]
TODO : demander à CBE d'ajouter une phrase sur la page du cours (https://webcampus.pasteur.fr/jcms/c_380246/formations-sur-le-campus#DebuterR2022).

> "Venir avec des données prêtes à analyser."
